coins = {
    "AXE":{
        "activate_with":"electrum",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": [{"url":"electrum1.cipig.net:10057"},
                     {"url":"electrum2.cipig.net:10057"},
                     {"url":"electrum3.cipig.net:10057"}],
    },
    "BAT":{
        "activate_with":"electrum",
        "api-id": "basic-attention-token",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
    },
    "BCH":{
        "activate_with":"electrum",
        "tx_explorer":"https://explorer.bitcoin.com/bch/tx",
        "electrum": [{"url":"electron.coinucopia.io:50001"},
                     {"url":"bch.imaginary.cash:50001"},
                     {"url":"wallet.satoshiscoffeehouse.com:50001"},
                     {"url":"electroncash.dk:50001"},
                     {"url":"electron-cash.dragon.zone:50001"}],
    },
    "BET":{
        "activate_with":"electrum",
        "electrum": [{"url": "electrum1.cipig.net:10012"},
                     {"url": "electrum2.cipig.net:10012"},
                     {"url": "electrum3.cipig.net:10012"},
                     {"url": "electrum1.cipig.net:20012",
                      "protocol": "SSL"},
                     {"url": "electrum2.cipig.net:20012",
                      "protocol": "SSL"},
                     {"url": "electrum3.cipig.net:20012",
                      "protocol": "SSL"}],
    },
    "BOTS":{
        "activate_with":"electrum",
        "tx_explorer":"https://bots.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10007"},
                     {"url":"electrum2.cipig.net:10007"},
                     {"url":"electrum3.cipig.net:10007"}],
    },
    "BTC":{
        "activate_with":"electrum",
        "tx_explorer":"https://explorer.bitcoin.com/btc/tx",
        "electrum": [{"url":"electrum1.cipig.net:10000"},
                     {"url":"electrum2.cipig.net:10000"},
                     {"url":"electrum3.cipig.net:10000"}],
    },
    "BTCH":{
        "activate_with":"electrum",
        "tx_explorer":"https://bots.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10020"},
                     {"url":"electrum2.cipig.net:10020"},
                     {"url":"electrum3.cipig.net:10020"}],
    },
    "BUSD":{
        "activate_with":"electrum",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
    },
    "CHIPS":{
        "activate_with":"electrum",
        "tx_explorer":"https://chips.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10053"},
                     {"url":"electrum2.cipig.net:10053"},
                     {"url":"electrum3.cipig.net:10053"}],
    },
    "COQUI":{
        "activate_with":"electrum",
        "tx_explorer":"https://coqui.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10011"},
                     {"url":"electrum2.cipig.net:10011"},
                     {"url":"electrum3.cipig.net:10011"}],
    },
    "CRYPTO":{
        "activate_with":"electrum",
        "tx_explorer":"https://crypto.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10008"},
                     {"url":"electrum2.cipig.net:10008"},
                     {"url":"electrum3.cipig.net:10008"}],
    },
    "DAI":{
        "activate_with":"electrum",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
    },
    "DASH":{
        "activate_with":"electrum",
        "tx_explorer":"https://explorer.dash.org/tx",
        "electrum":  [{"url":"electrum1.cipig.net:10061"},
                      {"url":"electrum2.cipig.net:10061"},
                      {"url":"electrum3.cipig.net:10061"}],
    },
    "DEX":{
        "activate_with":"electrum",
        "tx_explorer":"https://dex.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10006"},
                     {"url":"electrum2.cipig.net:10006"},
                     {"url":"electrum3.cipig.net:10006"}],
    },
    "DGB":{
        "activate_with":"electrum",
        "tx_explorer":"https://digiexplorer.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10059"},
                     {"url":"electrum2.cipig.net:10059"},
                     {"url":"electrum3.cipig.net:10059"}],
    },
    "DOGE":{
        "activate_with":"electrum",
        "tx_explorer":"https://live.blockcypher.com/doge/tx",
        "electrum": [{"url":"electrum1.cipig.net:10060"},
                     {"url":"electrum2.cipig.net:10060"},
                     {"url":"electrum3.cipig.net:10060"}],
    },
    "ECA":{
        "activate_with":"electrum",
        "electrum": [{"url": "electrum1.cipig.net:10052"},
                     {"url": "electrum2.cipig.net:10052"},
                     {"url": "electrum3.cipig.net:10052"},
                     {"url": "electrum1.cipig.net:20052",
                      "protocol": "SSL"},
                     {"url": "electrum2.cipig.net:20052",
                      "protocol": "SSL"},
                     {"url": "electrum3.cipig.net:20052",
                      "protocol": "SSL"}]
    },
    "EMC2":{
        "activate_with":"electrum",
        "electrum": [{"url": "electrum3.cipig.net:10062"},
                     {"url": "electrum2.cipig.net:10062"},
                     {"url": "electrum1.cipig.net:10062"}],
    },
    "ETH":{
        "activate_with":"electrum",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
    },
    "HODL":{
        "activate_with":"electrum",
        "electrum": [{"url": "electrum1.cipig.net:10009"},
                     {"url": "electrum2.cipig.net:10009"},
                     {"url": "electrum3.cipig.net:10009"},
                     {"url": "electrum1.cipig.net:20009",
                      "protocol": "SSL"},
                     {"url": "electrum2.cipig.net:20009",
                      "protocol": "SSL"},
                     {"url": "electrum3.cipig.net:20009",
                      "protocol": "SSL"}],
    },
    "HUSH":{
        "activate_with":"electrum",
        "tx_explorer":"https://hush3.komodod.com/",
        "electrum": [{"url":"electrum1.cipig.net:10064"},
                     {"url":"electrum2.cipig.net:10064"},
                     {"url":"electrum3.cipig.net:10064"}],
    },
    "ILN":{
        "activate_with":"electrum",
        "electrum": [{"url":"electrum1.ilien.io:65011"},
                     {"url":"electrum2.ilien.io:65011"}],
    },
    "JUMBLR":{
        "activate_with":"electrum",
        "electrum": [{"url": "electrum1.cipig.net:10004"},
                     {"url": "electrum2.cipig.net:10004"},
                     {"url": "electrum3.cipig.net:10004"},
                     {"url": "electrum1.cipig.net:20004",
                      "protocol": "SSL"},
                     {"url": "electrum2.cipig.net:20004",
                      "protocol": "SSL"},
                     {"url": "electrum3.cipig.net:20004",
                      "protocol": "SSL"}],
    },
    "KMD":{
        "activate_with":"electrum",
        "tx_explorer":"https://www.kmdexplorer.io/tx",
        "electrum": [{"url":"electrum1.cipig.net:10001"},
                     {"url":"electrum2.cipig.net:10001"},
                     {"url":"electrum3.cipig.net:10001"}],
    },
    "LABS":{
        "activate_with":"electrum",
        "tx_explorer":"https://labs.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10019"},
                     {"url":"electrum2.cipig.net:10019"},
                     {"url":"electrum3.cipig.net:10019"}],
    },
    "LINK":{
        "activate_with":"electrum",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
    },
    "LTC":{
        "activate_with":"electrum",
        "tx_explorer":"https://live.blockcypher.com/ltc/tx",
        "electrum": [{"url":"electrum-ltc.bysh.me:50001"},
                     {"url":"electrum.ltc.xurious.com:50001"},
                     {"url":"ltc.rentonisk.com:50001"},
                     {"url":"backup.electrum-ltc.org:50001"}],
    },
    "MCL":{
        "activate_with":"electrum",
        "electrum": [{"url": "electrum1.cipig.net:10023"},
                     {"url": "electrum2.cipig.net:10023"},
                     {"url": "electrum3.cipig.net:10023"},
                     {"url": "electrum1.cipig.net:20023",
                      "protocol": "SSL"},
                     {"url": "electrum2.cipig.net:20023",
                      "protocol": "SSL"},
                     {"url": "electrum3.cipig.net:20023",
                      "protocol": "SSL"}],
    },
    "MORTY":{
        "activate_with":"electrum",
        "tx_explorer":"https://morty.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10018"},
                     {"url":"electrum2.cipig.net:10018"},
                     {"url":"electrum3.cipig.net:10018"}],
    },
    "OOT":{
        "activate_with":"electrum",
        "tx_explorer":"https://oot.explorer.dexstats.info/tx",
        "electrum": [{"url": "electrum1.cipig.net:10021"},
                     {"url": "electrum2.cipig.net:10021"},
                     {"url": "electrum3.cipig.net:10021"},
                     {"url": "electrum1.cipig.net:20021",
                      "protocol": "SSL"},
                     {"url": "electrum2.cipig.net:20021",
                      "protocol": "SSL"},
                     {"url": "electrum3.cipig.net:20021",
                      "protocol": "SSL"}],
    },
    "PANGEA":{
        "activate_with": "electrum",
        "electrum": [{"url": "electrum1.cipig.net:10010"},
                     {"url": "electrum2.cipig.net:10010"},
                     {"url": "electrum3.cipig.net:10010"},
                     {"url": "electrum1.cipig.net:20010",
                      "protocol": "SSL"},
                     {"url": "electrum2.cipig.net:20010",
                      "protocol": "SSL"},
                     {"url": "electrum3.cipig.net:20010",
                      "protocol": "SSL"}],
    },
    "PAX":{
        "activate_with":"electrum",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
    },
    "QTUM":{
        "activate_with":"electrum",
        "tx_explorer":"https://qtum.info/tx",
        "electrum": [{"url":"s1.qtum.info:50001"},
                     {"url":"s2.qtum.info:50001"},
                     {"url":"s3.qtum.info:50001"},
                     {"url":"s4.qtum.info:50001"},
                     {"url":"s5.qtum.info:50001"},
                     {"url":"s6.qtum.info:50001"},
                     {"url":"s7.qtum.info:50001"},
                     {"url":"s8.qtum.info:50001"},
                     {"url":"s9.qtum.info:50001"}],
    },
    "REVS":{
        "activate_with":"electrum",
        "tx_explorer":"https://revs.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10003"},
                     {"url":"electrum2.cipig.net:10003"},
                     {"url":"electrum3.cipig.net:10003"}],
    },
    "RVN":{
        "activate_with":"electrum",
        "tx_explorer":"https://ravencoin.network/tx",
        "electrum": [{"url":"electrum1.cipig.net:10051"},
                     {"url":"electrum2.cipig.net:10051"},
                     {"url":"electrum3.cipig.net:10051"}],
    },
    "RFOX":{
        "activate_with":"electrum",
        "tx_explorer":"https://rfox.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10034"},
                     {"url":"electrum2.cipig.net:10034"},
                     {"url":"electrum3.cipig.net:10034"}],
    },
    "RICK":{
        "activate_with":"electrum",
        "tx_explorer":"https://rick.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10017"},
                     {"url":"electrum2.cipig.net:10017"},
                     {"url":"electrum3.cipig.net:10017"}],
    },
    "SUPERNET":{
        "activate_with":"electrum",
        "tx_explorer":"https://supernet.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10005"},
                     {"url":"electrum2.cipig.net:10005"},
                     {"url":"electrum3.cipig.net:10005"}],
    },
    "THC":{
        "activate_with":"electrum",
        "tx_explorer":"https://thc.explorer.dexstats.info/tx",
        "electrum": [{"url":"165.22.52.123:10022"},
                     {"url":"157.230.45.184:10022"}],
    },
    "TUSD":{
        "activate_with":"electrum",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
    },
    "USDC":{
        "activate_with":"electrum",
        "tx_explorer":"https://etherscan.io/tx",
        "electrum": ["http://eth1.cipig.net:8555",
                     "http://eth2.cipig.net:8555",
                     "http://eth3.cipig.net:8555"],
        "contract": "0x8500AFc0bc5214728082163326C2FF0C73f4a871",
    },
    "VRSC":{
        "activate_with":"electrum",
        "tx_explorer":"https://explorer.veruscoin.io/tx",
        "electrum": [{"url": "el0.veruscoin.io:17485"},
                     {"url": "el1.veruscoin.io:17485"},
                     {"url": "el2.veruscoin.io:17485"}],
    },
    "WLC":{
        "activate_with":"electrum",
        "tx_explorer":"https://wlc.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10014"},
                     {"url":"electrum2.cipig.net:10014"},
                     {"url":"electrum3.cipig.net:10014"}],
    },
    "XZC":{
        "activate_with":"electrum",
        "electrum": [{"url": "electrumx.zcoin.io:50001",
                      "protocol": "TCP"},
                     {"url": "electrumx01.zcoin.io:50001",
                      "protocol": "TCP"},
                     {"url": "electrumx02.zcoin.io:50001",
                      "protocol": "TCP"},
                     {"url": "electrumx03.zcoin.io:50001",
                      "protocol": "TCP"}]
    },
    "ZEC":{
        "activate_with":"electrum",
        "tx_explorer":"https://explorer.zcha.in/transactions",
        "electrum": [{"url":"electrum3.cipig.net:10058"},
                     {"url":"electrum3.cipig.net:10058"},
                     {"url":"electrum3.cipig.net:10058"}],
    },
    "ZILLA":{
        "activate_with":"electrum",
        "tx_explorer":"https://zilla.explorer.dexstats.info/tx",
        "electrum": [{"url":"electrum1.cipig.net:10028"},
                     {"url":"electrum2.cipig.net:10028"},
                     {"url":"electrum3.cipig.net:10028"}],
    }
}
